apiVersion: apps/v1
kind: Deployment
metadata:
  name: malrang-redis
  labels:
    db: malrang-redis
spec:
  selector:
    matchLabels:
      db: malrang-redis
  template:
    metadata:
      labels:
        db: malrang-redis
    spec:
      containers:
        - name: malrang-redis
          image: redis:latest
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
          command: [ "redis-server", "--requirepass", "1248" ]

---

apiVersion: v1
kind: Service
metadata:
  name: malrang-redis
  labels:
    db: malrang-redis
spec:
  type: ClusterIP
  selector:
    db: malrang-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379