apiVersion: v1
kind: Service
metadata:
  name: malrang-service
spec:
  selector:
    app: malrang
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: malrang-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: malrang
  template:
    metadata:
      labels:
        app: malrang
    spec:
      containers:
        - name: malrang
          image: malrang:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/test_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1248"
