# MySQL JDBC Driver Class
spring:
  cloud:
    config:
      enabled: false  # Config Server ????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  # SQL Show Configuration (true: show, false: hide)
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
      format_sql: true
      properties:
        hibernate:
          ddl-auto: create
          format_sql: true
          dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  # Include OAuth Properties
  profiles:
    include: oauth

  # Server Encoding Configuration
  servlet:
    encoding:
      force-response: true

  # Error Handling Configuration
  error:
    whitelabel:
      enabled: false
    path: /error

# ChatGPT API Key
api-key:
  chat_gpt: ${CHAT_GPT_API_KEY}

# JWT Configuration
jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}



