apiVersion: v1
kind: Service
metadata:
  name: malrang-service
  labels:
    app: malrang-service
spec:
  type: ClusterIP
  selector:
    app: malrang-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001